### ISSUE TITLE
[Feature request] Open remote URL in browser

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#112]
### 1. Request

It would be nice, if you add `Open remote issue URL in browser` feature.

### 2. Justification

I need to preview my Markdown markup, that to see my markup error. Yes, I can use [**Markmon**](http://ru.stackoverflow.com/a/549194/199934), but Markmon Markdown to HTML compilation may be difference that GitHub Markdown to HTML compilation. Better preview markup on GitHub.

### 3. Desirable behavior

I wrote and post, for example, this issue → <kbd>Ctrl+Shift+P</kbd> → `GitHub Issue: Open Remote Issue URL In Browser` → **<https://github.com/divinites/gissues/issues/112>** page open for me in my browser.

### 4. Examples on other apps

In [**Sublime-GitHub**](https://packagecontrol.io/packages/sublime-github) package we have a feature [**Open Remote URL In Browser**](https://github.com/bgreenlee/sublime-github/blob/master/Github.sublime-commands#L15). Similar feature are in [**GitHubinator**](https://packagecontrol.io/packages/GitHubinator) and [**GitLink**](https://packagecontrol.io/packages/GitLink) packages.

Thanks.

**Comment by divinites** [comment]
Hi, Kristinita,  I think we already have quite a few plug-ins that can open remote url in browser, why we couldn't simply use another package for that?

**Comment by Kristinita** [comment]
> Hi, Kristinita, I think we already have quite a few plug-ins that can open remote url in browser, why we couldn't simply use another package for that?

@divinites , I write and post issue use GitHub Issue. How I can open remote issue URL in browser? Which packages I need to use?

Thanks.

**Comment by divinites** [comment]
I see, so you want to open the issue that you are currently writing in the browser

**Comment by divinites** [comment]
Function added in version 3.3.0 issue closed.

**Comment by Kristinita** [comment]
Thank you, it works for me!
