### ISSUE TITLE
建议 readme 补充两点说明

### ISSUE THREAD

**Issue by cyio** [divinites/gissues#17]
1. 重启编辑器，插件才能工作
2. 需要设置access_token，插件才能工作

**Comment by divinites** [comment]
哈哈，因为FitchFoll还没有来得及审核这个package，所以还没有上架package control channel，想不到这么快就有人用了。建议很好，我这就修改。
已经完成 See commitment fcbcc29cac24aaa022a18f1432aac81e24071780.
Issue closed.
