### ISSUE TITLE
[Feature-request] Change cursor position

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#44]
### Request

Please make sure that after I select `GitHub Issue: Create Issue`, the cursor would have been after the `Title`.
### Justification

To ensure that users do not press additionally keys on the keyboard or mouse buttons.
### Extended behavior

![Extended](http://i.imgur.com/TGUmuPm.png)
### Actual behavior

![Actual](http://i.imgur.com/XKb4imf.png)

Thanks.

**Comment by divinites** [comment]
Wow, one issue sloved, two others emerge.

**Comment by divinites** [comment]
the last commit 79437e2 solved this issue, version 1.2.6
