### ISSUE TITLE
[Bug] Only 30 last issues were visible

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#51]
### Summary

In issue list is visible only 30 last issues.
### Expected behavior

All issues were visible.
### Actual behavior

![Actual](http://i.imgur.com/phTG1Ih.png)
### Steps to reproduce

<kbd>Ctrl+Shift+P</kbd> → `GitHub Issue: Show All Issue List...` → `manually enter repository...` → `divinites/gissues` → I saw only 30 last issues.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by divinites** [comment]
Found the reason!

GitHub has automatically pagination to avoid obtainning thousands of issues at a time. 

I will design a workaround for this problem. Maybe "->" and "<-" will be used to turn pages in the new version.

**Comment by divinites** [comment]
@Kristinita It is not a trivial project to solve this bug. I designed something like this for issue pagination, am I missing something?

![pagination](https://cloud.githubusercontent.com/assets/7761537/19150035/bd97efb2-8bbc-11e6-8f05-47fcc6883cdd.gif)

**Comment by Kristinita** [comment]
@divinites , excellent solution! Release?

**Comment by divinites** [comment]
@Kristinita, No, currently the interface works but I have not really coded the pagniation behaviour.There is something not in GitHub's online API document, I just digged it out and need further design the actual code structure. I will let you know when ready.

**Comment by divinites** [comment]
@Kristinita  version 1.5.0, I finally solved the pagination issue.  See the picture below for an overview!

![ttt](https://cloud.githubusercontent.com/assets/7761537/19188094/5cffd52c-8c87-11e6-80f3-932439fb80b3.gif)
