### ISSUE TITLE
404?

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#69]
None!

**Comment by divinites** [comment]
@Kristinita Since you are using Markdown GFM syntax instead of the built-in issue.sublime-syntax, could you please tell me if auto-completion feature works for you? the newest version just added commit auto-completion: a251d62bab211d6a26adfa5489ca03aeb903ca97  so now almost everything is auto-completable such as label, other issues, discussants and commits.

**Comment by Kristinita** [comment]
@divinites , please, may you add in `README.MD` screencasts of extended behavior auto-completion? Now I do not know how should work your autocompletes. Thanks.

**Comment by divinites** [comment]
@Kristinita I have added two screenshots. One for label auto-completion, the other for issue title, commits and participants auto-completion.

**Comment by Kristinita** [comment]
@divinites , none autocomplete not work for me 😿. Thanks.

**Comment by divinites** [comment]
Yes, it is understandable. @Kristinita if you open `github_issue.sublime-settings`, you will find it has been updated.

``` json
{
    "token": "",
    "username": "",
    "password": "",
    "debug": 0,
    "syntax": "Packages/GitHubIssue/Issue.sublime-syntax",
    "git_path": "",
    "issue_title_completion": true,
    "user_completion": true,
    "label_completion": true,
    "commit_completion": true,
    "commit_completion_trigger": ":",
    "custom_completion_scope": []

}
```

fill in the "custom_completion_scope" with your markdown scope, if you are using Markdown GFM, then In your user setting file, it  should be:

``` json
    "custom_completion_scope": ["text.html.markdown.gfm"]
```

If it does not work, please let me know the console output.

**Comment by divinites** [comment]
Also,

> none autocomplete not work for me

is double negative, which actually means that all autocompletes work for you. I believe that it is not the meaning that you want to express.

**Comment by Kristinita** [comment]
> is double negative, which actually means that all autocompletes work for you. I believe that it is not the meaning that you want to express.

I'm sorry, I know English bad. You also incorrectly wrote a [message in Russian language](https://github.com/divinites/gissues/issues/52#issuecomment-252455407) 😸.

### Not automatically autocomplete

@divinites, now all autocompletes works for me, but I need press <kbd>Ctrl+Space</kbd>, to get autocomplete variants. 

I find in my `User/Preferences.sublime-settings` file these lines

``` json
"auto_complete_triggers":
[
    {
        "characters": "<",
        "selector": "text.html"
    },
    {
        "characters": "@",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "#",
        "selector": "text.html.github.issue"
    },
    {
        "characters": ":",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "@",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "#",
        "selector": "text.html.github.issue"
    },
    {
        "characters": ":",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "@",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "#",
        "selector": "text.html.github.issue"
    },
    {
        "characters": ":",
        "selector": "text.html.github.issue"
    }
],
```

Selector not automatically change for me.

### Commit trigger

I think that the symbol `:` a bad solution to commit trigger by default, because symbol `:` use on GitHub for smiles. I use [GitHub Emoji](https://github.com/akatopo/GithubEmoji) plugin, after `:` I get smiles in autocomplete.

![Smiles autocomplete](http://i.imgur.com/FC0Tzcv.png)

Thanks.

**Comment by divinites** [comment]
commit & 45877c4eb3fdf36512e9f7ce8e47fc5533f20b5f should solve this problem. The selector will be your custom_scope and it will not make duplicated entries in perference.sublime-settings.  Please  delete

``` json
    {
        "characters": "@",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "#",
        "selector": "text.html.github.issue"
    },
    {
        "characters": ":",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "@",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "#",
        "selector": "text.html.github.issue"
    },
    {
        "characters": ":",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "@",
        "selector": "text.html.github.issue"
    },
    {
        "characters": "#",
        "selector": "text.html.github.issue"
    },
    {
        "characters": ":",
        "selector": "text.html.github.issue"
    }
```

In the file.

I will push a new release soon.

**Comment by divinites** [comment]
pushed v.2.3.2. @Kristinita

**Comment by divinites** [comment]
pushed v.2.3.5. Now the auto-completion feature is constrained inside the view, so it will not save in the disk and jeopardizes preferences.sublime-settings. @Kristinita now you can delete all trigger settings that this plug-in adds. I believe the initial settings is just:

``` json
"auto_complete_triggers":
[
    {
        "characters": "<",
        "selector": "text.html"
    }
],
```
