### ISSUE TITLE
active_issue_obj is None

### ISSUE THREAD

**Issue by DamnWidget** [divinites/gissues#93]
Hi @divinites, I tried the plugin today but is not working at all for me. 

OS: Linux
ST3 Build: 3126
GitHubIssues Version: 3.2.1 

I always get the following error in the console:
```
Traceback (most recent call last):
  File "github_issue in /home/damnwidget/.config/sublime-text-3/Installed Packages/GitHubIssue.sublime-package", line 199, in on_enter_repo_info
  File "github_issue in /home/damnwidget/.config/sublime-text-3/Installed Packages/GitHubIssue.sublime-package", line 229, in print_issue_list
AttributeError: 'NoneType' object has no attribute 'get_repo_info'
```

I am using a token with full control over my Github account.

**Comment by divinites** [comment]
Hi, Thanks for your feedback, could you please follow  these steps:
- set the debug trigger to 1, e.g.

``` json
{
    "token": "xxx",
    "username": "xxx",
    "debug": 1,

}
```
-  restart sublime Text.
-  paste the console output here?

**Comment by DamnWidget** [comment]
Looks like it just needed a ST3 restart, you should probably add a note in the installation/configuration section of the README.md file.

Thanks :)

**Comment by divinites** [comment]
@DamnWidget  Thanks! will put a note of special attention in readme.md then.
